### ISSUE TITLE
MMB v2 data missing

### ISSUE THREAD

**Issue by BlackNet** [bigtreetech/MMB#14]
*ALL* Github data is missing for the MMB V2 board.  Please add that ASAP

**Comment by bigtreetech** [comment]
What MMB V2 board?

**Comment by BlackNet** [comment]
The second version of the MMB board is now shipping.

**Comment by bigtreetech** [comment]
Nope, there is no official second version and most certainly nothing shipping.

**Comment by BlackNet** [comment]
Please explain this then.

![mmb-v2-2](https://github.com/user-attachments/assets/7b4a1eac-efa1-40db-9d4e-9c9b44f73a82)

![mmb-v2-1](https://github.com/user-attachments/assets/98614add-6ccb-4b52-92f9-0d6e37397fe5)

**Comment by bigtreetech** [comment]
Are you a part of a beta program?

**Comment by BlackNet** [comment]
No, I am not. It was received via regular channels on an open purchase.
